import { Treasure } from './types';

export const TREASURES: Treasure[] = [
  { id: 'crab', emoji: '🦀', name: 'Hermit Crab', color: 'bg-red-500/20' },
  { id: 'puffer', emoji: '🐡', name: 'Pufferfish', color: 'bg-yellow-500/20' },
  { id: 'shell', emoji: '🐚', name: 'Conch Shell', color: 'bg-orange-200/20' },
  { id: 'coral', emoji: '🪸', name: 'Coral', color: 'bg-pink-500/20' },
  { id: 'octopus', emoji: '🐙', name: 'Octopus', color: 'bg-purple-500/20' },
  { id: 'squid', emoji: '🦑', name: 'Squid', color: 'bg-pink-400/20' },
  { id: 'fish-tropical', emoji: '🐠', name: 'Tropical Fish', color: 'bg-yellow-400/20' },
  { id: 'fish-blue', emoji: '🐟', name: 'Blue Tang', color: 'bg-blue-500/20' },
  { id: 'dolphin', emoji: '🐬', name: 'Dolphin', color: 'bg-cyan-500/20' },
  { id: 'whale', emoji: '🐳', name: 'Spouting Whale', color: 'bg-blue-600/20' },
  { id: 'shark', emoji: '🦈', name: 'Shark', color: 'bg-gray-500/20' },
  { id: 'seal', emoji: '🦭', name: 'Seal', color: 'bg-stone-400/20' },
  { id: 'turtle', emoji: '🐢', name: 'Sea Turtle', color: 'bg-green-500/20' },
  { id: 'lobster', emoji: '🦞', name: 'Lobster', color: 'bg-red-600/20' },
  { id: 'shrimp', emoji: '🦐', name: 'Shrimp', color: 'bg-orange-400/20' },
  { id: 'anchor', emoji: '⚓', name: 'Lost Anchor', color: 'bg-slate-500/20' },
  { id: 'coin', emoji: '🪙', name: 'Doubloon', color: 'bg-yellow-600/20' },
  { id: 'diamond', emoji: '💎', name: 'Sunken Gem', color: 'bg-cyan-300/20' },
  { id: 'trident', emoji: '🔱', name: 'Trident', color: 'bg-yellow-300/20' },
  { id: 'mermaid', emoji: '🧜‍♀️', name: 'Mermaid', color: 'bg-purple-400/20' },
  { id: 'island', emoji: '🏝️', name: 'Islet', color: 'bg-green-300/20' },
  { id: 'wave', emoji: '🌊', name: 'Big Wave', color: 'bg-blue-400/20' },
  { id: 'boat', emoji: '⛵', name: 'Sailboat', color: 'bg-white/20' },
  { id: 'compass', emoji: '🧭', name: 'Compass', color: 'bg-orange-700/20' },
  { id: 'map', emoji: '🗺️', name: 'Treasure Map', color: 'bg-amber-200/20' },
  { id: 'pearl', emoji: '⚪', name: 'Black Pearl', color: 'bg-gray-400/20' },
  { id: 'jellyfish', emoji: '🎐', name: 'Jellyfish', color: 'bg-pink-200/20' }, // Wind chime looks like jellyfish
  { id: 'crocodile', emoji: '🐊', name: 'Saltwater Croc', color: 'bg-green-700/20' },
  { id: 'duck', emoji: '🦆', name: 'Lost Duck', color: 'bg-yellow-700/20' },
  { id: 'flamingo', emoji: '🦩', name: 'Flamingo', color: 'bg-pink-600/20' },
];
